# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcdWindow.ui'
#
# Created: Wed Nov  8 04:17:59 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 272)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutMain = QtGui.QGridLayout(self.centralwidget)
        self.gridLayoutMain.setObjectName("gridLayoutMain")
        self.groupBoxInfo = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBoxInfo.setFont(font)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.gridLayoutInfo = QtGui.QGridLayout(self.groupBoxInfo)
        self.gridLayoutInfo.setObjectName("gridLayoutInfo")
        self.labelBank = QtGui.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelBank.setFont(font)
        self.labelBank.setObjectName("labelBank")
        self.gridLayoutInfo.addWidget(self.labelBank, 1, 0, 1, 1)
        self.checkBoxPedalMode = QtGui.QCheckBox(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxPedalMode.setFont(font)
        self.checkBoxPedalMode.setCheckable(True)
        self.checkBoxPedalMode.setObjectName("checkBoxPedalMode")
        self.gridLayoutInfo.addWidget(self.checkBoxPedalMode, 1, 3, 1, 1)
        self.checkBoxBypass = QtGui.QCheckBox(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxBypass.setFont(font)
        self.checkBoxBypass.setCheckable(True)
        self.checkBoxBypass.setObjectName("checkBoxBypass")
        self.gridLayoutInfo.addWidget(self.checkBoxBypass, 2, 3, 1, 1)
        self.checkBoxMute = QtGui.QCheckBox(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxMute.setFont(font)
        self.checkBoxMute.setCheckable(True)
        self.checkBoxMute.setObjectName("checkBoxMute")
        self.gridLayoutInfo.addWidget(self.checkBoxMute, 3, 3, 1, 1)
        self.labelPresetName = QtGui.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelPresetName.setFont(font)
        self.labelPresetName.setObjectName("labelPresetName")
        self.gridLayoutInfo.addWidget(self.labelPresetName, 3, 0, 1, 1)
        self.lcdNumberPreset = QtGui.QLCDNumber(self.groupBoxInfo)
        self.lcdNumberPreset.setMinimumSize(QtCore.QSize(180, 30))
        self.lcdNumberPreset.setDigitCount(3)
        self.lcdNumberPreset.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberPreset.setObjectName("lcdNumberPreset")
        self.gridLayoutInfo.addWidget(self.lcdNumberPreset, 2, 1, 1, 1)
        self.checkBoxEnabled = QtGui.QCheckBox(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxEnabled.setFont(font)
        self.checkBoxEnabled.setObjectName("checkBoxEnabled")
        self.gridLayoutInfo.addWidget(self.checkBoxEnabled, 4, 3, 1, 1)
        self.labelPreset = QtGui.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelPreset.setFont(font)
        self.labelPreset.setObjectName("labelPreset")
        self.gridLayoutInfo.addWidget(self.labelPreset, 2, 0, 1, 1)
        self.lineEditWebAddress = QtGui.QLineEdit(self.groupBoxInfo)
        self.lineEditWebAddress.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditWebAddress.setFont(font)
        self.lineEditWebAddress.setReadOnly(True)
        self.lineEditWebAddress.setObjectName("lineEditWebAddress")
        self.gridLayoutInfo.addWidget(self.lineEditWebAddress, 4, 1, 1, 1)
        self.lineEditPresetName = QtGui.QLineEdit(self.groupBoxInfo)
        self.lineEditPresetName.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditPresetName.setFont(font)
        self.lineEditPresetName.setReadOnly(True)
        self.lineEditPresetName.setObjectName("lineEditPresetName")
        self.gridLayoutInfo.addWidget(self.lineEditPresetName, 3, 1, 1, 1)
        self.labelWebAddress = QtGui.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelWebAddress.setFont(font)
        self.labelWebAddress.setObjectName("labelWebAddress")
        self.gridLayoutInfo.addWidget(self.labelWebAddress, 4, 0, 1, 1)
        self.lcdNumberBank = QtGui.QLCDNumber(self.groupBoxInfo)
        self.lcdNumberBank.setMinimumSize(QtCore.QSize(180, 30))
        self.lcdNumberBank.setDigitCount(3)
        self.lcdNumberBank.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumberBank.setObjectName("lcdNumberBank")
        self.gridLayoutInfo.addWidget(self.lcdNumberBank, 1, 1, 1, 1)
        self.labelRemoteID = QtGui.QLabel(self.groupBoxInfo)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelRemoteID.setFont(font)
        self.labelRemoteID.setObjectName("labelRemoteID")
        self.gridLayoutInfo.addWidget(self.labelRemoteID, 5, 0, 1, 1)
        self.lineEditRemoteID = QtGui.QLineEdit(self.groupBoxInfo)
        self.lineEditRemoteID.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditRemoteID.setFont(font)
        self.lineEditRemoteID.setReadOnly(True)
        self.lineEditRemoteID.setObjectName("lineEditRemoteID")
        self.gridLayoutInfo.addWidget(self.lineEditRemoteID, 5, 1, 1, 1)
        self.checkBoxPaired = QtGui.QCheckBox(self.groupBoxInfo)
        self.checkBoxPaired.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxPaired.setFont(font)
        self.checkBoxPaired.setCheckable(True)
        self.checkBoxPaired.setObjectName("checkBoxPaired")
        self.gridLayoutInfo.addWidget(self.checkBoxPaired, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutInfo.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayoutMain.addWidget(self.groupBoxInfo, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pedal Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBank.setText(QtGui.QApplication.translate("MainWindow", "Bank:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPedalMode.setText(QtGui.QApplication.translate("MainWindow", "Pedal Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBypass.setText(QtGui.QApplication.translate("MainWindow", "Bypass", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMute.setText(QtGui.QApplication.translate("MainWindow", "Mute", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPresetName.setText(QtGui.QApplication.translate("MainWindow", "Preset Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEnabled.setText(QtGui.QApplication.translate("MainWindow", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreset.setText(QtGui.QApplication.translate("MainWindow", "Preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWebAddress.setText(QtGui.QApplication.translate("MainWindow", "Web Address: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRemoteID.setText(QtGui.QApplication.translate("MainWindow", "Remote ID: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPaired.setText(QtGui.QApplication.translate("MainWindow", "Paired", None, QtGui.QApplication.UnicodeUTF8))

